site_name: Duon Registry
copyright: © 2023-2024 ebene fünf GmbH
nav:
  - Documentation:
    - index.md
theme:
  name: duon
repo_url: https://github.com/duon/registry
extra:
  project: Registry
plugins:
  - search
  - macros:
      module_name: docs/main
markdown_extensions:
  - admonition
  - pymdownx.snippets:
      base_path: [".", "docs/code"]